<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<TcPlcObject ProductVersion="3.1.0.18" Version="1.1.0.1">
  <POU Name="alg_a_TledQ1">
    <Declaration><![CDATA[FUNCTION alg_a_TledQ1: BOOL
VAR_INPUT
    state: STATE;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[alg_a_TledQ1 := (state.dvar_M_led1) = (elit_On);]]></ST>
    </Implementation>
    <ObjectProperties/>
  </POU>
</TcPlcObject>
